name: "Download All Target Comparison Artifacts"
description: "Downloads all the artifacts for all targets needed for run comparison"
inputs:
  gcchash:
    required: true
  token:
    required: true
  repo:
    required: true

runs:
  using: "composite"
  steps:
    # reports
    - name: Download linux rv64 bitmanip multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-linux-rv64gc_zba_zbb_zbc_zbs-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: gcc-linux-rv64gc_zba_zbb_zbc_zbs-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}
        repo: ${{ inputs.repo }}

    - name: Download linux rv64 vector multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-linux-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: gcc-linux-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}
        repo: ${{ inputs.repo }}

    - name: Download newlib rv64 vector multilib
      uses: ./.github/actions/common/download-comparison-artifacts
      with:
        report-artifact-name: gcc-newlib-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib-report.log
        binary-artifact-name: gcc-newlib-rv64gcv-lp64d-${{ inputs.gcchash }}-multilib
        github-token: ${{ inputs.token }}
        repo: ${{ inputs.repo }}

    # End download
