name: "Download Build Artifacts"
description: "Downloads artifacts needed for build log comparison"
inputs:
  build-artifact-name:
    required: true
  github-token:
    required: true
  output-dir:
    required: true
    description: 'Absolute path to the output directory'

runs:
  using: "composite"
  steps:
    - name: Download Build log using action
      if: ${{ !cancelled() }}
      id: same-workflow
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build-artifact-name }}
        path: ${{ inputs.output-dir }}
        repository: patrick-rivos/gcc-postcommit-ci
      continue-on-error: true

    # If an artifact cannot be donwloaded using the action, use the download script instead
    - name: Download Build log using script
      if: ${{ !cancelled() && steps.same-workflow.outcome == 'failure' }}
      id: other-workflow
      shell: bash
      run: |
        cd riscv-gnu-toolchain
        python ./scripts/download_artifact.py -name ${{ inputs.build-artifact-name }} -repo patrick-rivos/gcc-postcommit-ci -token ${{ inputs.github-token }} -outdir ${{ inputs.output-dir }}
      continue-on-error: true
