name: "Report Build Complete Status"
description: "create report and posts to patchwork"
inputs:
  build_status:
    description: 'Build status'
    required: true
  patch_name:
    description: 'Name of patch'
    required: true
  build_log_name:
    description: 'Name of build log'
    required: true
  target:
    description: 'libc-arch-abi-multilib'
    required: true
  baseline_hash:
    description: 'baseline gcc hash'
    required: true
  tot_hash:
    description: 'tip of tree gcc hash'
    required: true
  issue_num:
    description: 'issue id'
    required: true
  build_comment_id:
    description: 'comment id'
    required: true
  additional_info:
    description: 'link to issue comment'
    required: true
  github_token:
    description: 'github token'
    required: true
  patchwork_token:
    description: 'patchwork token'
    required: true

runs:
  using: "composite"
  steps:
      - name: Build success report
        if: ${{ inputs.build_status == 'success' }}
        shell: bash
        working-directory: riscv-gnu-toolchain
        run: |
          export HASH=${{ inputs.baseline_hash }}
          python scripts/update_issue_status.py -token ${{ inputs.github_token }} -state 'Success' -comment ${{ inputs.build_comment_id }} -target ${{ inputs.target }} -check 'Build GCC' -repo ewlu/gcc-precommit-ci -baseline $HASH
          printf "\n[Additional information](${{ inputs.additional_info }})\n" >> comment.md

      - name: Build failure report
        if: ${{ inputs.build_status == 'failure' }}
        shell: bash
        working-directory: riscv-gnu-toolchain
        run: |
          export HASH=${{ inputs.baseline_hash }}
          python scripts/update_issue_status.py -token ${{ inputs.github_token }} -state 'Build failure. Please check the ${{ inputs.build_log_name }} artifact' -comment ${{ inputs.build_comment_id }} -target ${{ inputs.target }} -check 'Build GCC' -repo ewlu/gcc-precommit-ci -baseline $HASH
          printf "\n[Additional information](${{ inputs.additional_info }})\n" >> comment.md

      - name: Update build complete report comment
        uses: ./.github/actions/update-comment
        with:
          comment_id: ${{ inputs.build_comment_id }}
          file_path: riscv-gnu-toolchain/comment.md
          token: ${{ inputs.github_token }}

      - name: Add build-failure label
        if: ${{ inputs.build_status == 'failure' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ inputs.issue_num }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['build-failure']
            })

      - name: Report error on build-failure
        if: ${{ inputs.build_status == 'failure' }}
        shell: bash
        working-directory: riscv-gnu-toolchain
        run: |
          python scripts/post_check_to_patchworks.py -event ${{ github.event_name }} -repo ewlu/gcc-precommit-ci -pid $(tail -n 1 patches/${{ inputs.patch_name }})  -desc 'Build failed' -iid '${{ inputs.issue_num }}#issuecomment-${{ inputs.build_comment_id }}' -state 'fail' -context 'build--${{ inputs.target }}' -token '${{ inputs.patchwork_token }}'
        continue-on-error: true

      - name: Report build success
        if: ${{ inputs.build_status == 'success' }}
        shell: bash
        working-directory: riscv-gnu-toolchain
        run: |
          python scripts/post_check_to_patchworks.py -event ${{ github.event_name }} -repo ewlu/gcc-precommit-ci -pid $(tail -n 1 patches/${{ inputs.patch_name }})  -desc 'Build passed' -iid '${{ inputs.issue_num }}#issuecomment-${{ inputs.build_comment_id }}' -state 'success' -context 'build--${{ inputs.target }}' -token '${{ inputs.patchwork_token }}'
        continue-on-error: true

