name: "Run testsuite"
description: "Runs testsuite"
inputs:
  mode:
    description: 'libc'
    required: true
  target:
    description: 'target arch-abi'
    required: true
  gcchash:
    description: 'gcchash'
    required: true
  multilib:
    description: 'is multilib'
    required: true

runs:
  using: "composite"
  steps:
      - name: Run testsuite
        shell: bash
        working-directory: riscv-gnu-toolchain
        run: |
          cd build
          make -j 32 report-${{ inputs.mode }} || true

      - name: Build debug log
        shell: bash
        working-directory: riscv-gnu-toolchain
        run: |
          if [ "${{ inputs.mode }}" == "newlib" ]; then
            cat `find build/build-gcc-newlib-stage2/gcc/testsuite/ -name g*.log` > gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-debug-output.log
          else
            cat `find build/build-gcc-linux-stage2/gcc/testsuite/ -name g*.log` > gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-debug-output.log
          fi

      - name: Upload debug artifacts
        id: debug-artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-debug-output.log
          path: |
            riscv-gnu-toolchain/gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-debug-output.log
          retention-days: 90

      - name: Build artifact url artifact
        shell: bash
        working-directory: riscv-gnu-toolchain
        run: |
          echo "${{ inputs.mode }}-${{ inputs.target }} testsuite logs: ${{ steps.debug-artifact.outputs.artifact-url }}" > gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-debug-url.md
          cat gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-debug-url.md

      - name: Upload artifact url artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-debug-url.md
          path: |
            riscv-gnu-toolchain/gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-debug-url.md
          retention-days: 90

      - name: Build sum files
        shell: bash
        working-directory: riscv-gnu-toolchain
        run: |
          mkdir sum_files
          if [ "${{ inputs.mode }}" == "newlib" ]; then
            for file in `find build/build-gcc-newlib-stage2/gcc/testsuite/ -name g*.sum`; do cp $file sum_files; done
          else
            for file in `find build/build-gcc-linux-stage2/gcc/testsuite/ -name g*.sum`; do cp $file sum_files; done
          fi

      - name: Upload sum file artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-sum-files
          path: |
            riscv-gnu-toolchain/sum_files
          retention-days: 90

      - name: Save results
        shell: bash
        working-directory: riscv-gnu-toolchain
        run: |
          if [ "${{ inputs.mode }}" == "newlib" ]; then
            PARSE_EXISTING_REPORT="./scripts/testsuite-filter gcc newlib test/allowlist `find build/build-gcc-newlib-stage2/gcc/testsuite/ -name *.sum |paste -sd "," -`"
          else
            PARSE_EXISTING_REPORT="./scripts/testsuite-filter gcc glibc test/allowlist `find build/build-gcc-linux-stage2/gcc/testsuite/ -name *.sum |paste -sd "," -`"
          fi
          $PARSE_EXISTING_REPORT | tee gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-report.log || true

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-report.log
          path: |
            riscv-gnu-toolchain/gcc-${{ inputs.mode }}-${{ inputs.target }}-${{ inputs.gcchash }}-${{ inputs.multilib }}-report.log
          retention-days: 90
