name: "Intialize submodules"

# Upload the sources as an artifact for other steps to use
# This centralizes the process and reduces overall compute time

on:
  workflow_call:
    inputs:
      baseline_hash:
        required: false
        type: string
      tot_hash:
        required: false
        type: string
    outputs:
        baseline_hash:
          value: ${{ jobs.init-submodules.outputs.baseline_hash }}
        tot_hash:
          value: ${{ jobs.init-submodules.outputs.tot_hash }}

jobs:
  init-submodules:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: riscv-gnu-toolchain

    steps:
      - uses: actions/checkout@v3

      - name: Clone riscv-gnu-toolchain
        working-directory: ./
        run: |
          git submodule update --init riscv-gnu-toolchain

      - name: Determine baseline
        id: baseline-hash
        run: |
          python ./scripts/get_baseline_hash.py -token ${{ secrets.GITHUB_TOKEN }}

          if [ '${{ inputs.baseline_hash }}' == '' ] ; then export BASELINE_HASH=$(cat baseline.txt); else export BASELINE_HASH=${{ inputs.baseline_hash }}; fi
          echo $BASELINE_HASH
          echo "baseline_hash=$BASELINE_HASH" >> $GITHUB_OUTPUT

      - name: Retrieve cache
        id: retrieve-cache
        uses: actions/cache@v3
        with:
          path: |
            riscv-gnu-toolchain/.git
            riscv-gnu-toolchain/binutils
            riscv-gnu-toolchain/dejagnu
            riscv-gnu-toolchain/gcc
            riscv-gnu-toolchain/gdb
            riscv-gnu-toolchain/glibc
            riscv-gnu-toolchain/newlib
            riscv-gnu-toolchain/qemu
          key: submodules-archive-8 # Numbered archive to allow for easy transition when bumping submodules

      - name: Initalize submodules cache
        if: steps.retrieve-cache.outputs.cache-hit != 'true'
        run: |
          git submodule update --init --recursive --depth 1 binutils
          git submodule update --init --recursive --depth 1 dejagnu
          git submodule update --init --recursive --depth 1 gdb
          git submodule update --init --recursive --depth 1 glibc
          git submodule update --init --recursive --depth 1 newlib
          git submodule update --init --recursive --depth 1 qemu
          rm -rf gcc
          git clone git://gcc.gnu.org/git/gcc.git

      - name: Apply newlib fixups
        if: steps.retrieve-cache.outputs.cache-hit != 'true'
        run: |
          cd newlib
          git config --global user.email "github-bot@example.com"
          git config --global user.name "Github Bot"
          git am ../fixups/newlib/*.patch

      - name: Determine tip-of-tree hash
        working-directory: riscv-gnu-toolchain/gcc
        id: tot-hash
        run: |
          git checkout master
          git pull
          if [ '${{ inputs.tot_hash }}' != '' ]; then git checkout ${{ inputs.tot_hash }}; fi
          export TOT_HASH=$(git rev-parse HEAD)
          echo $TOT_HASH
          echo "tot_hash=$TOT_HASH" >> $GITHUB_OUTPUT

      - name: Checkout baseline GCC hash
        working-directory: riscv-gnu-toolchain/gcc
        run: |
          git checkout ${{ steps.baseline-hash.outputs.baseline_hash }}

      - name: Cache submodules
        if: steps.retrieve-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            riscv-gnu-toolchain/.git
            riscv-gnu-toolchain/binutils
            riscv-gnu-toolchain/dejagnu
            riscv-gnu-toolchain/gcc
            riscv-gnu-toolchain/gdb
            riscv-gnu-toolchain/glibc
            riscv-gnu-toolchain/newlib
            riscv-gnu-toolchain/qemu
          key: submodules-archive-8

      - name: Make cache zip
        run: |
          zip -r cache.zip .git binutils dejagnu gcc gdb glibc newlib qemu

      # Use artifact rather than cache since cache downloads are flaky/hang.
      # Artifacts are reliable but ~30 min slower to set up.
      # Setup is done on one runner, so this isn't a show stopper.
      - name: Upload git cache
        uses: actions/upload-artifact@v3
        with:
          name: gcc-sources-${{ steps.baseline-hash.outputs.baseline_hash }}
          path: |
            riscv-gnu-toolchain/cache.zip
          retention-days: 5

    outputs:
      baseline_hash: ${{ steps.baseline-hash.outputs.baseline_hash }}
      tot_hash: ${{ steps.tot-hash.outputs.tot_hash }}
