name: Issue-Closer

on:
  schedule:
    # Run nightly at 2:17
    # https://stackoverflow.com/questions/59560214/github-action-works-on-push-but-not-scheduled
    - cron: 17 2 * * *

jobs:
  close-issues:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: riscv-gnu-toolchain
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/common/setup-env
        with:
          free_up_space: false

      - name: Install dependencies
        run: |
          sudo apt install python3 -y
          sudo apt install python-is-python3 -y
          sudo apt install zip -y

      - name: Setup python env
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install -U pyopenssl cryptography
          python -m pip install pygithub==1.59.1 requests

      - name: Close issues
        run: |
          python scripts/close_old_issues.py -token ${{ secrets.GITHUB_TOKEN }}

