name: Issue-Closer

on:
  schedule:
    # Run nightly at 2:17
    # https://stackoverflow.com/questions/59560214/github-action-works-on-push-but-not-scheduled
    - cron: 17 2 * * *

jobs:
  close-issues:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: riscv-gnu-toolchain
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup env
        uses: ./.github/actions/common/setup-env
        with:
          free_up_space: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          pip install -r ../requirements.txt

      - name: Install dependencies
        run: |
          sudo apt install zip -y

      - name: Close issues
        run: |
          python scripts/close_old_issues.py -token ${{ secrets.GITHUB_TOKEN }}
