name: Lint

on:
  workflow_call:
    inputs:
      patch_name:
        required: true
        type: string
      issue_num:
        required: true
        type: string
      lint_comment_id:
        required: true
        type: string
      additional_info:
        required: true
        type: string
      baseline_hash:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-20.04
    environment: production
    permissions:
      issues: write
    defaults:
      run:
        working-directory: riscv-gnu-toolchain
    steps:
      - uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/common/setup-env
        with:
          free_up_space: false

      - name: Restore submodules from cache
        uses: actions/download-artifact@v3
        with:
          name: gcc-sources-${{ inputs.baseline_hash }}
          path: ./riscv-gnu-toolchain

      - name: Restore submodules
        run: |
          rm -rf .git binutils dejagnu gcc gdb glibc newlib qemu
          unzip cache.zip
          rm -rf cache.zip

      - name: Download patches artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.patch_name }}-downloaded-patches
          path: ./riscv-gnu-toolchain

      - name: Extract patches
        run: |
          unzip ${{ inputs.patch_name }}-downloaded-patches.zip

      - name: Install prereqs
        run: |
          pip3 install termcolor unidiff

      - name: Report start linter
        run: |
          python scripts/post_check_to_patchworks.py -event ${{ github.event_name }} -repo ewlu/gcc-precommit-ci -pid $(tail -n 1 patches/${{ inputs.patch_name }})  -desc 'Lint starting' -iid '${{ inputs.issue_num }}#issuecomment-${{ inputs.lint_comment_id }}' -state 'pending' -context 'lint' -token ${{ secrets.PATCHWORK_API }}

      # Only lint the last patch in the series since that's where the warning will be displayed
      - name: Lint patch
        id: lint
        run: |
          let patches_and_metadata_count=$(ls -1 patches | wc -l)
          let patches_count=$((patches_and_metadata_count / 2))
          python ./gcc/contrib/check_GNU_style.py "./patches/patch-$patches_count.patch" 2>&1 | tee "lint_results.txt"
          if (($(cat lint_results.txt | wc -l) > 0)); then
            echo "lint_failed=true" >> $GITHUB_OUTPUT
          else
            echo "lint_failed=false" >> $GITHUB_OUTPUT
          fi

      - name: Create linter report
        if: ${{ steps.lint.outputs.lint_failed == 'true' }}
        run: |
          python ./scripts/generate_linter_fail_report.py --linter-log lint_results.txt --patch-name ${{ inputs.patch_name }}

      - name: Build lint failed comment report # reduce the number of lines in final comment so github always creates comment
        if: ${{ steps.lint.outputs.lint_failed == 'true' }}
        run: |
          echo "## Lint Status" > comment.md
          cat linter_fail_report.md >> comment.md
          head -c 65000 comment.md > trimmed_comment.md
          if [ $(cat trimmed_comment.md | wc -l) -ne $(cat comment.md | wc -l) ]; then printf "\n\`\`\`\nComment text has been trimmed. Please check logs for the untrimmed comment.\nLogs -> \<patch name\> -> lint -> Lint patch step" >> trimmed_comment.md; fi
          printf "\n[Additional information](${{ inputs.additional_info }})\n" >> trimmed_comment.md

      - name: Update lint failed comment report
        if: ${{ steps.lint.outputs.lint_failed == 'true' }}
        uses: peter-evans/create-or-update-comment@v3
        id: lint-fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          comment-id: ${{ inputs.lint_comment_id }}
          body-path: riscv-gnu-toolchain/trimmed_comment.md
          edit-mode: replace

      - name: Add linter-failure Label to issue
        if: ${{ steps.lint.outputs.lint_failed == 'true' }}
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: ${{ inputs.issue_num }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['linter-failure']
            })

      - name: Report linter warning
        if: ${{ steps.lint.outputs.lint_failed == 'true' }}
        run: |
          python scripts/post_check_to_patchworks.py -event ${{ github.event_name }} -repo ewlu/gcc-precommit-ci -pid $(tail -n 1 patches/${{ inputs.patch_name }})  -desc 'Lint failed' -iid '${{ inputs.issue_num }}#issuecomment-${{ inputs.lint_comment_id }}' -state 'warning' -context 'lint' -token ${{ secrets.PATCHWORK_API }}

      - name: Make lint passed comment
        if: ${{ steps.lint.outputs.lint_failed == 'false' }}
        run: |
          echo "## Lint Status" > lint_passed.md
          echo "Lint passed" >> lint_passed.md

      - name: Update lint passed comment report
        if: ${{ steps.lint.outputs.lint_failed == 'false' }}
        uses: peter-evans/create-or-update-comment@v3
        id: lint-pass
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          comment-id: ${{ inputs.lint_comment_id }}
          body-path: riscv-gnu-toolchain/lint_passed.md
          edit-mode: replace

      - name: Report linter success
        if: ${{ steps.lint.outputs.lint_failed == 'false' }}
        run: |
          python scripts/post_check_to_patchworks.py -event ${{ github.event_name }} -repo ewlu/gcc-precommit-ci -pid $(tail -n 1 patches/${{ inputs.patch_name }})  -desc 'Lint passed' -iid '${{ inputs.issue_num }}#issuecomment-${{ inputs.lint_comment_id }}' -state 'success' -context 'lint' -token ${{ secrets.PATCHWORK_API }}
